# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6df6475cac0b92e98a69abaa9ae81318cb2d9281ffbd8feaaa1bec6cf07e7cbf17230a33e63087539db50159fb506a31f50d11e84aee5e6fa27bdf7a92573c38

test:
  secret_key_base: a130320ed350502958e99ad1ca48068b3002045a0dc4695a7b2aaa5a4e784750c9d264efcc8e8a05eb34642a023603ff3e40e26688226a5dbb201ee38b1fd52d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
